# Generated by Django 4.0.4 on 2022-06-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'db_carrito_producto',
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('suscrito', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'db_suscriptor',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
                ('confirmar_contrasena', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_usuario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('plu_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('preciooferta', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=80)),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoproducto')),
            ],
            options={
                'db_table': 'db_producto',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu_codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrito_producto')),
            ],
            options={
                'db_table': 'db_Historial',
            },
        ),
        migrations.AddField(
            model_name='carrito_producto',
            name='plu_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto'),
        ),
    ]
