# Generated by Django 4.0.4 on 2022-07-07 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
    ]
