# Generated by Django 4.0.4 on 2022-05-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrito_producto_carrito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='nombre',
            new_name='nombre_producto',
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='precio',
            new_name='precio_producto',
        ),
    ]
