# Generated by Django 4.0.4 on 2022-07-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_suscriptor_remove_usuario_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('suscrito', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'db_suscriptor',
            },
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='precio',
            new_name='precio_producto',
        ),
    ]
