# Generated by Django 4.0.4 on 2022-05-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_nombre_carrito_producto_nombre_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito_producto',
            name='preciooferta',
            field=models.IntegerField(null=True),
        ),
    ]
