# Generated by Django 4.0.4 on 2022-07-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_suscriptor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='descripcion',
            new_name='descripcion_car',
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='imagen',
            new_name='imagen_car',
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='nombre',
            new_name='nombre_car',
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='precio_producto',
            new_name='precio_car',
        ),
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='preciooferta',
            new_name='preciooferta_car',
        ),
    ]
