# Generated by Django 4.0.4 on 2022-07-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_descripcion_carrito_producto_descripcion_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_producto',
            name='totales',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
