# Generated by Django 4.0.4 on 2022-05-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_carrito_producto_preciooferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_producto',
            name='descripcion_producto',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
