# Generated by Django 4.0.4 on 2022-07-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrito_producto_totales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='usuario',
            new_name='usuario_car',
        ),
    ]
