# Generated by Django 4.0.4 on 2022-05-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carrito_producto_descripcion_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito_producto',
            name='descripcion_producto',
        ),
    ]
