# Generated by Django 4.0.4 on 2022-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_carrito_producto_descripcion_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_producto',
            name='descripcion_producto',
            field=models.CharField(default='no hay desc', max_length=100),
            preserve_default=False,
        ),
    ]
