# Generated by Django 4.0.4 on 2022-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_usuario_carrito_producto_usuario_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('productos', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_pedido',
            },
        ),
    ]
