# Generated by Django 4.0.4 on 2022-05-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_carrito_producto_descripcion_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_producto',
            old_name='descripcion_producto',
            new_name='descripcion',
        ),
    ]
