# Generated by Django 4.0.4 on 2022-05-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_descripcion_producto_carrito_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=20)),
                ('confirmar_contrasena', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'db_usuario',
            },
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
