# Generated by Django 4.0.4 on 2022-07-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('Entregando a Currier', 'Entregando a Currier'), ('En Camino', 'En Camino'), ('Entregado', 'Entregado')], max_length=25),
        ),
    ]
