# Generated by Django 4.0.4 on 2022-07-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado_Pedido',
        ),
    ]
