# Generated by Django 4.0.4 on 2022-07-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_usuario_usuario_usuariodjango'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuarioDjango',
            new_name='usuario',
        ),
    ]
